enum CODE_ACTION_TYPE {
  BIND = 'BIND',
  REPLACE = 'REPLACE',
  UNBIND = 'UNBIND',
  RESET = 'RESET',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  EDIT_PASSWORD = 'EDIT_PASSWORD',
  FORGET_PASSWORD = 'FORGET_PASSWORD',
  COMMON = 'COMMON'
}

export {
  CODE_ACTION_TYPE
}

